# ----------------------------------------------------------
# DataStax Enterprise Java Driver Config
# ----------------------------------------------------------
cassandra:
  contactPoint: 127.0.0.1
  port: 9042
  keyspaceName: kara
  localDataCenterName: datacenter1
  dropSchema: false
server:
  port: 8082
